# Generated by Django 4.0.4 on 2022-04-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('answer', models.TextField(verbose_name='답변')),
                ('create_at', models.DateTimeField(verbose_name='작성일')),
            ],
        ),
    ]
