# Generated by Django 4.0.4 on 2022-04-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('일반', '일반'), ('계정', '계정'), ('기타', '기타')], default='일반', max_length=2, verbose_name='카태고리')),
            ],
        ),
    ]
